### PR TITLE
add .travis.yml config file, closes #4

### LINKED ISSUE #4: Add .travis.yml config file to repo

### PR DESCRIPTION
**Pull request by lorecrafting**

### CODE REVIEW

**Comment by shockey** [comment]
@TheWhiteOx Why are there three Node versions listed?

**Comment by lorecrafting** [comment]
In the build file we can specificy different node versions that Travis will run the build/test process against so that in case we move environments we'll know the info.  I'll take off the other node versions since we're probably just going to deploy to one version/environment.

**Comment by shockey** [comment]
+1

**Comment by MyNameIsKir** [comment]
+1

**Pull request merged**
